VeryGoodOpenSource/very_good_flutter_plugin

- tool/generator/main.dart
- feat: improve test variable names
> feat: improve test variable names

- brick/brick.yaml
- tool/generator/main.dart
- refactor: use lambda shorthand syntax
> refactor: use lambda shorthand syntax

- brick/brick.yaml
- tool/generator/main.dart
- tool/generator/static/{{~ plugin_dependencies.dart }}
- tool/generator/static/{{~ plugin_platforms.dart }}
- feat: support conditional platform plugins
> feat: support conditional platform plugins

- .github/workflows/generate_template.yaml
- ci(generate_template): use macos
> ci(generate_template): use macos

- tool/generator/static/{{~ plugin_platforms.dart }}
> fix: platforms partial

- .github/workflows/my_plugin.yaml
- .github/workflows/my_plugin_android.yaml
- .github/workflows/my_plugin_ios.yaml
- .github/workflows/my_plugin_linux.yaml
- .github/workflows/my_plugin_macos.yaml
- .github/workflows/my_plugin_platform_interface.yaml
- .github/workflows/my_plugin_web.yaml
- .github/workflows/my_plugin_windows.yaml
- src/my_plugin/example/analysis_options.yaml
- src/my_plugin/example/lib/main.dart
- src/my_plugin/example/linux/flutter/generated_plugins.cmake
- src/my_plugin/example/pubspec.yaml
- src/my_plugin/example/windows/flutter/generated_plugins.cmake
- src/my_plugin/pubspec.yaml
- src/my_plugin_android/pubspec.yaml
- src/my_plugin_ios/pubspec.yaml
- src/my_plugin_linux/pubspec.yaml
- src/my_plugin_macos/pubspec.yaml
- src/my_plugin_platform_interface/pubspec.yaml
- src/my_plugin_web/pubspec.yaml
- src/my_plugin_windows/pubspec.yaml
- refactor: upgrade to Flutter 3.0.0
> refactor: upgrade to Flutter 3.0.0

- src/my_plugin/analysis_options.yaml
- src/my_plugin/example/analysis_options.yaml
- src/my_plugin/example/pubspec.yaml
- src/my_plugin/pubspec.yaml
- src/my_plugin_android/pubspec.yaml
- src/my_plugin_ios/pubspec.yaml
- src/my_plugin_linux/analysis_options.yaml
- src/my_plugin_linux/pubspec.yaml
- src/my_plugin_macos/analysis_options.yaml
- src/my_plugin_macos/pubspec.yaml
- src/my_plugin_platform_interface/analysis_options.yaml
- src/my_plugin_platform_interface/pubspec.yaml
- src/my_plugin_web/analysis_options.yaml
- src/my_plugin_web/pubspec.yaml
- src/my_plugin_windows/analysis_options.yaml
- src/my_plugin_windows/pubspec.yaml
- chore(deps): very_good_analysis ^3.0.0
> chore(deps): very_good_analysis ^3.0.0

- src/my_plugin/analysis_options.yaml
- src/my_plugin/example/analysis_options.yaml
- src/my_plugin/example/pubspec.yaml
- src/my_plugin/pubspec.yaml
- src/my_plugin_android/analysis_options.yaml
- src/my_plugin_android/pubspec.yaml
- src/my_plugin_ios/analysis_options.yaml
- src/my_plugin_ios/pubspec.yaml
- src/my_plugin_linux/analysis_options.yaml
- src/my_plugin_linux/pubspec.yaml
- src/my_plugin_macos/analysis_options.yaml
- src/my_plugin_macos/pubspec.yaml
- src/my_plugin_platform_interface/analysis_options.yaml
- src/my_plugin_platform_interface/pubspec.yaml
- src/my_plugin_web/analysis_options.yaml
- src/my_plugin_web/pubspec.yaml
- src/my_plugin_windows/analysis_options.yaml
- src/my_plugin_windows/pubspec.yaml
- refactor: upgrade to very_good_analysis v3.0.1
> refactor: upgrade to very_good_analysis v3.0.1

- src/my_plugin/example/integration_test/app_test.dart
- tool/generator/main.dart
Fixing multiple files and directory that should adhere to the platform flags.
> fix: use platform flags for all platform related files and directories

- .github/dependabot.yaml
- .github/workflows/my_plugin.yaml
- .github/workflows/my_plugin_android.yaml
- .github/workflows/my_plugin_ios.yaml
- .github/workflows/my_plugin_linux.yaml
- .github/workflows/my_plugin_macos.yaml
- .github/workflows/my_plugin_platform_interface.yaml
- .github/workflows/my_plugin_web.yaml
- .github/workflows/my_plugin_windows.yaml
- src/my_plugin/my_plugin/analysis_options.yaml
- src/my_plugin/my_plugin/example/analysis_options.yaml
- src/my_plugin/my_plugin/example/pubspec.yaml
- src/my_plugin/my_plugin/pubspec.yaml
- src/my_plugin/my_plugin_android/analysis_options.yaml
- src/my_plugin/my_plugin_android/pubspec.yaml
- src/my_plugin/my_plugin_ios/analysis_options.yaml
- src/my_plugin/my_plugin_ios/pubspec.yaml
- src/my_plugin/my_plugin_linux/analysis_options.yaml
- src/my_plugin/my_plugin_linux/pubspec.yaml
- src/my_plugin/my_plugin_macos/analysis_options.yaml
- src/my_plugin/my_plugin_macos/pubspec.yaml
- src/my_plugin/my_plugin_platform_interface/analysis_options.yaml
- src/my_plugin/my_plugin_platform_interface/pubspec.yaml
- src/my_plugin/my_plugin_web/analysis_options.yaml
- src/my_plugin/my_plugin_web/pubspec.yaml
- src/my_plugin/my_plugin_windows/analysis_options.yaml
- src/my_plugin/my_plugin_windows/pubspec.yaml
- feat: upgrade to Flutter 3.3.1 and very_good_analysis 3.0.2
> feat: upgrade to Flutter 3.3.1 and very_good_analysis 3.0.2

- .github/workflows/my_plugin.yaml
- .github/workflows/my_plugin_android.yaml
- .github/workflows/my_plugin_ios.yaml
- .github/workflows/my_plugin_linux.yaml
- .github/workflows/my_plugin_macos.yaml
- .github/workflows/my_plugin_platform_interface.yaml
- .github/workflows/my_plugin_web.yaml
- .github/workflows/my_plugin_windows.yaml
- src/my_plugin/my_plugin/analysis_options.yaml
- src/my_plugin/my_plugin/example/analysis_options.yaml
- src/my_plugin/my_plugin/example/pubspec.yaml
- src/my_plugin/my_plugin/pubspec.yaml
- src/my_plugin/my_plugin_android/analysis_options.yaml
- src/my_plugin/my_plugin_android/pubspec.yaml
- src/my_plugin/my_plugin_ios/analysis_options.yaml
- src/my_plugin/my_plugin_ios/pubspec.yaml
- src/my_plugin/my_plugin_linux/analysis_options.yaml
- src/my_plugin/my_plugin_linux/pubspec.yaml
- src/my_plugin/my_plugin_macos/analysis_options.yaml
- src/my_plugin/my_plugin_macos/pubspec.yaml
- src/my_plugin/my_plugin_platform_interface/analysis_options.yaml
- src/my_plugin/my_plugin_platform_interface/pubspec.yaml
- src/my_plugin/my_plugin_web/analysis_options.yaml
- src/my_plugin/my_plugin_web/pubspec.yaml
- src/my_plugin/my_plugin_windows/analysis_options.yaml
- src/my_plugin/my_plugin_windows/pubspec.yaml
- feat: upgrade to Flutter 3.3.2 and Very Good Analysis 3.1.0
> feat: upgrade to Flutter 3.3.2 and Very Good Analysis 3.1.0

- .github/dependabot.yaml
> fix: dependabot file

- src/my_plugin/my_plugin/analysis_options.yaml
- src/my_plugin/my_plugin/example/analysis_options.yaml
- src/my_plugin/my_plugin/example/pubspec.yaml
- src/my_plugin/my_plugin/pubspec.yaml
- src/my_plugin/my_plugin_android/analysis_options.yaml
- src/my_plugin/my_plugin_android/pubspec.yaml
- src/my_plugin/my_plugin_ios/analysis_options.yaml
- src/my_plugin/my_plugin_ios/pubspec.yaml
- src/my_plugin/my_plugin_linux/analysis_options.yaml
- src/my_plugin/my_plugin_linux/pubspec.yaml
- src/my_plugin/my_plugin_macos/analysis_options.yaml
- src/my_plugin/my_plugin_macos/pubspec.yaml
- src/my_plugin/my_plugin_platform_interface/analysis_options.yaml
- src/my_plugin/my_plugin_platform_interface/pubspec.yaml
- src/my_plugin/my_plugin_web/analysis_options.yaml
- src/my_plugin/my_plugin_web/pubspec.yaml
- src/my_plugin/my_plugin_windows/analysis_options.yaml
- src/my_plugin/my_plugin_windows/pubspec.yaml
- chore: upgrade to very_good_analysis 4.0.0
> chore: upgrade to very_good_analysis 4.0.0

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.3.1

- .github/workflows/my_plugin.yaml
- src/my_plugin/my_plugin_ios/ios/Classes/MyPluginPlugin.swift
> fix: integration tests

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.3.2

- tool/generator/main.dart
> fix: updated pana workflow regex matching

- patches/android/pubspec_publish.patch
- patches/android/workflow_pana.patch
- patches/ios/pubspec_publish.patch
- patches/ios/workflow_pana.patch
- patches/linux/pubspec_publish.patch
- patches/linux/workflow_pana.patch
- patches/macos/pubspec_publish.patch
- patches/macos/workflow_pana.patch
- patches/plugin/pubspec_publish.patch
- patches/plugin/workflow_pana.patch
- patches/web/pubspec_publish.patch
- patches/web/workflow_pana.patch
- patches/windows/pubspec_publish.patch
- patches/windows/workflow_pana.patch
- src/my_plugin/my_plugin/analysis_options.yaml
- src/my_plugin/my_plugin/pubspec.yaml
- src/my_plugin/my_plugin_android/analysis_options.yaml
- src/my_plugin/my_plugin_android/pubspec.yaml
- src/my_plugin/my_plugin_ios/analysis_options.yaml
- src/my_plugin/my_plugin_ios/pubspec.yaml
- src/my_plugin/my_plugin_linux/analysis_options.yaml
- src/my_plugin/my_plugin_linux/pubspec.yaml
- src/my_plugin/my_plugin_macos/analysis_options.yaml
- src/my_plugin/my_plugin_macos/pubspec.yaml
- src/my_plugin/my_plugin_platform_interface/analysis_options.yaml
- src/my_plugin/my_plugin_platform_interface/pubspec.yaml
- src/my_plugin/my_plugin_web/analysis_options.yaml
- src/my_plugin/my_plugin_web/pubspec.yaml
- src/my_plugin/my_plugin_windows/analysis_options.yaml
- src/my_plugin/my_plugin_windows/pubspec.yaml
Support Dart SDK to 2.18.0 since VeryGoodCli supports 2.18.0 (see [this](https://github.com/VeryGoodOpenSource/very_good_cli/pull/679)).
> chore: support dart sdk 2.18.0

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.3.3

- brick/CHANGELOG.md
- brick/brick.yaml
- brick/hooks/pubspec.yaml
> chore: v0.4.0

- .github/workflows/my_plugin.yaml
- .github/workflows/my_plugin_android.yaml
- .github/workflows/my_plugin_ios.yaml
chore: standardize Flutter version
> chore: standardize flutter version

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.5.0

- README.md
docs: update readme redirecting usage to the cli website
fix: #123
> docs: update readme redirecting usage to the cli website

- brick/hooks/pubspec.yaml
- brick/hooks/test/pre_gen_test.dart
**READY**
Adds test to pre_gen.dart
> test: add pre generation tests

- README.md
**READY**
Fixing a typo reported by a community member in #144
> docs: update README "using the brick" section typo

- brick/hooks/lib/src/cli/cli.dart
- brick/hooks/lib/src/cli/command_line.dart
- brick/hooks/lib/src/cli/dart_cli.dart
- brick/hooks/lib/src/cli/very_good_cli.dart
- brick/hooks/lib/very_good_flutter_plugin_hooks.dart
- brick/hooks/pubspec.yaml
- brick/hooks/test/cli/command_line_test.dart
- brick/hooks/test/cli/dart_cli_test.dart
- brick/hooks/test/cli/very_good_cli_test.dart
- brick/hooks/test/post_gen_test.dart
**READY**
Defines `DartCli` and `VeryGoodCli`.
This is to be followed by another Pull Requests that uses these CLIs to get packages, format and fix the output.
Related to #141.
Changes:
- Adds `DartCli`
- Adds `VeryGoodCli`
- Renames hooks package name to use "plugin" (plural) over "plugins"
> feat(very_good_flutter_plugin_hooks): define Dart and Very Good CLI classes

- .github/workflows/sync_labels.yaml
**READY**
Add label sync action
> chore: add label sync

- src/my_plugin/my_plugin/example/actions/check_platform_name/lib/src/check_platform_name.dart
- src/my_plugin/my_plugin/example/actions/check_platform_name/test/src/check_platform_name_test.dart
> fix: add support for platform testing
